.TH IPK-CLIENT 1
.SH NAME
ipk\-client \- connects to master server and receive mathematical orders and send the results
.SH SYNOPSIS
.B ipk\-client
\fIADDRESS\fR
.SH DESCRIPTION
.B ipk\-client
connects to a server specified in \fIADDRESS\fR. First it sends \fBHELLO\fR message with MD5 hash of the student, that created it. Then the server sends to the client mathematical orders in specified format (\fB SOLVE\fR \fIOPERAND_1\fR \fIOPERATION\fR \fIOPERAND_2\fR\\n), then it performs the computing and sends back the result in specified format (\fBRESULT\fR \fIDECIMAL_NUMBER\fR). The client ends the connection after it receives \fBBYE\fR message with \fISECRET\fR, then the client prints the \fISECRET\fR and terminates.
.SH OPTIONS
.TP
.BR \fIADDRESS\fR
Address of the master server.

